name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.2
    - name: Configure Project
      uses: threeal/cmake-action@v1.3.0
    - name: Build Project
      run: cmake --build build
    - name: Test Project
      id: testing123
      run: ctest --test-dir build
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        TESTING123_RESULTS: "${{ steps.testing123.outcome }}"
      with:
        runners: testing123
        