name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Configure, Build, and Test Project
      uses: threeal/cmake-action@v1.3.0
      with:
        run-build: true
        run-test: true
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        TESTING123_RESULTS: "${{ steps.run-autograding-tests.outcome }}"
      with:
        runners: testing123
        